'use strict';
const branches = [
  {title:'书页里的回声',relation:'渐渐熟悉',narrative:'林晚从书架第三层抽出一本薄薄的诗集。封面已经褪色，书脊却被细心地修补过。她把书放在你面前，又将台灯转过一点。',extra:'你翻开第一页，看见一片压平的银杏叶。叶脉像一张微小的地图，指向某个已经过去的秋天。窗外的雨还没有停，但你忽然不那么着急了。街角的末班电车缓缓驶过，玻璃上的光影也随之移动。',dialogue:'“这本书不用从第一页读起。随便翻开一页，如果某句话让你停下来，那就是今晚的答案。”',choices:['读一读夹着银杏叶的那页','问问这本书的来历']},
  {title:'一封迟到的信',relation:'分享秘密',narrative:'柜台上的牛皮纸信封没有邮票，收件人一栏只写着“雨天来借书的人”。林晚看了它一眼，笑意中多了一点惊讶。',extra:'信封压在一本旧地图册下面，纸角已经微微卷起。她说，这封信是前任店主留下的，每年雨季都会拿出来，却始终没有找到合适的收件人。你仔细看着那行字，发现笔画间有一枚小小的月亮。或许有些消息，并不是为了赶时间而写下的。',dialogue:'“它在这里等了很久。信没有署名，里面只有一句话：如果你还愿意走远一点，书店后面有一座桥。”',choices:['请她讲讲那座桥','将信留给下一个雨天']},
  {title:'留一盏灯',relation:'安心相处',narrative:'林晚没有再问，只搬来一把靠窗的椅子。茶杯轻轻落在桌面上，你身后的门合上了，雨声也变得遥远。',extra:'你看着窗上的水珠，一颗追上另一颗，慢慢汇成细小的河流。屋里只有翻书的声音和旧挂钟的滴答声。你忽然发现，自己已经很久没有这样安静地坐着。林晚在另一端整理着归还的书，没有催促，也没有刻意搭话。',dialogue:'“那就坐一会儿。这里不要求每位客人都买书，也不要求每段沉默都有一个理由。”',choices:['捧起热茶，看看窗外','帮她整理桌上的旧书']}
];
const opening={title:'意外来客',relation:'初次见面',narrative:'雨声敲在青石巷的屋檐上，你拾起衣领，推开了那扇亮着灯的木门。店里很安静，空气中是纸张与茶叶的气息。店主正在收拾书架，听见动静，转过身来。',extra:'门上的铜铃只响了一声。门边摆着一把还在滴水的伞，柜台旁的挂钟停在九点四十七分。你不知道它是刚刚停下，还是已经停了很久。屋里的人似乎并不介意时间，林晚把手里的书合上，为你留出一小块干燥的桌面。',dialogue:'“进来吧。雨停之前，这里还有一盏灯。你想找一本怎样的书？”',choices:['一本能让人安静下来的书','先问问那封没有署名的信','我只是想躲一会儿雨']};
let chapter=0,branch=0,long=false;
const $=id=>document.getElementById(id);
function current(){if(chapter===0)return opening;if(chapter===1)return branches[branch];return {title:'下一次，晴天见',relation:'约好再见',narrative:['你翻到夹着银杏叶的那页，读到一句关于远行的诗。窗外的雨渐渐停了，林晚把那片书签送给了你。','你将那封信轻轻收好。也许明天，也许某个不赶时间的下午，你会走过书店后面的那座桥。','桌上的旧书回到了各自的位置，茶杯也空了。你推门时，发现巷子里多了一弯月光。'][branch],extra:'走出店门的时候，你回头看了一眼。那盏灯依然亮着，照着尚未合上的书页。城市还有很多没有读完的故事，而你知道，有一个地方总可以慢慢读。这一夜的相遇暂时落幕，下一次的故事留给下一场雨。',dialogue:'“今天就到这里吧。下次来的时候，记得告诉我，你后来读到了什么。”',choices:['回到开场，选择另一条故事线']};}
function render(){const s=current();$('chapter-title').textContent=['第一章','第二章','第三章'][chapter]+' · '+s.title;$('chapter-count').textContent=String(chapter+1).padStart(2,'0')+' / 03';$('time').textContent=['21:47','21:55','22:08'][chapter];$('weather').textContent=chapter===2?'雨歇':'小雨';$('relationship').textContent=s.relation;const narrative=$('narrative');narrative.replaceChildren();for(const text of long?[s.narrative,s.extra]:[s.narrative]){const p=document.createElement('p');p.textContent=text;narrative.append(p);}$('dialogue').textContent=s.dialogue;$('choices').replaceChildren(...s.choices.map((text,i)=>{const b=document.createElement('button');b.type='button';b.className='choice';const n=document.createElement('span');n.className='choice-number';n.textContent=String(i+1).padStart(2,'0');const label=document.createElement('span');label.textContent=text;const arrow=document.createElement('span');arrow.className='choice-arrow';arrow.textContent='→';arrow.setAttribute('aria-hidden','true');b.append(n,label,arrow);b.addEventListener('click',()=>{if(chapter===2){reset();return;}if(chapter===0)branch=i;chapter++;render();$('announcement').textContent='已进入'+$('chapter-title').textContent;$('chapter-title').tabIndex=-1;$('chapter-title').focus({preventScroll:true});if(window.innerWidth<761)$('story').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});});return b;}));}
function reset(){chapter=0;long=false;$('length').setAttribute('aria-pressed','false');$('length').innerHTML='展开长文 <span aria-hidden="true">＋</span>';$('response').value='';$('send').disabled=true;$('response-copy').textContent='';$('response-history').hidden=true;render();$('announcement').textContent='故事已重置，回到第一章。';}
document.querySelectorAll('[data-theme]').forEach(button=>button.addEventListener('click',()=>{document.body.dataset.style=button.dataset.theme;document.querySelectorAll('[data-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('announcement').textContent=button.textContent+'样式已启用。';}));
$('length').addEventListener('click',()=>{long=!long;$('length').setAttribute('aria-pressed',String(long));$('length').innerHTML=long?'收起长文 <span aria-hidden="true">－</span>':'展开长文 <span aria-hidden="true">＋</span>';render();});
$('reset').addEventListener('click',reset);$('response').addEventListener('input',()=>{$('send').disabled=!$('response').value.trim();});$('response-form').addEventListener('submit',event=>{event.preventDefault();const value=$('response').value.trim();if(!value)return;$('response-copy').textContent=value;$('response-history').hidden=false;$('response').value='';$('send').disabled=true;$('announcement').textContent='你的回应已在本地展示。没有上传或生成自动回复。';});render();
